[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/=lib/openzeppelin-contracts/contracts', 'forge-std/=lib/forge-std/src', 'safe/=lib/safe-contracts/contracts']
fuzz_runs = 256
gas_reports = ["*"]
eth-rpc-url = 'https://mainnet.infura.io/v3/9928b52099854248b3a096be07a6b23c'
solc_version = '0.8.10'
[fmt]
line_length = 120

# See more config options https://github.com/foundry-rs/foundry/tree/master/config